### PR TITLE
Port date commands to enqine-q

### PR DESCRIPTION
**Pull request by onthebridgetonowhere**
I ported the date commands to engine-q. One thing I am not sure about is the `to-table` command. The result is a "column" table and not a "row" table. Is my understanding correct that 1-row tables are automatically pivoted to vertical tables?

Looking forward to feedback :-)

Issue reference: https://github.com/nushell/engine-q/issues/242

### CODE REVIEW

**Comment by jntrnr** [comment]
@onthebridgetonowhere - in engine-q, there's finally a difference between a record and a one-row table. If you make a Record and put it in a Stream or List, you'll get the one row table.

**Comment by jntrnr** [comment]
@onthebridgetonowhere - just reviewed it, well done! this looks great.

Last step is that you'll need to run through `cargo clippy --all` and fix the warnings you see. With that I think we're good.

**Comment by onthebridgetonowhere** [comment]
@jntrnr thanks for the review and suggestions. Fixed the one-row table issue as well as all clippy issues.

**Comment by jntrnr** [comment]
Heh, this is reminding me we should use nicer test assertions :D  Looks like the difference is between Record and List of a single Record on the failing test.

**Comment by onthebridgetonowhere** [comment]
Fixed the failing test case.

**Comment by jntrnr** [comment]
looks good!

**Pull request merged**
