### PR TITLE
Fix term width for the table

### PR DESCRIPTION
**Pull request by jntrnr**
Do a similar calculation for width to what we do in nushell

### CODE REVIEW

**Comment by fdncred** [comment]
nice! glad you found this. let me ask another question. i think i did this btw - but e-q uses `terminal_size` instead of `term_size`, which nushell uses. I noticed `miette` uses `term_size` as well, so we already have a dependency on it, indirectly i guess. do we want to switch to `term_size` or just leave it. i'm guessing i picked `terminal_size` because it was update more recently. also because `term_size` has been archived.

**Comment by jntrnr** [comment]
@fdncred yeah, we might want to PR the change to Miette to move to the more supported thing.

**Comment by zkat** [comment]
@fdncred @jntrnr FYI I noticed this issue and just released `miette@3.3.0`, which uses `terminal_size` instead.

**Comment by jntrnr** [comment]
@zkat - thank you!

**Pull request merged**
