### PR TITLE
Add Path commands

### PR DESCRIPTION
**Pull request by LiHRaM**
The Path commands as listed in #242 

- [x] PathCommand
- [x] PathBasename
- [x] PathDirname
- [x] PathExists
- [x] PathExpand
- [x] PathJoin
- [x] PathParse
- [x] PathRelative
- [x] PathSplit
- [x] PathType

### CODE REVIEW

**Comment by kubouch** [comment]
@LiHRaM Just checking in -- did you manage to continue on this? I'm largely responsible for the Nushell's path commands and happy to help if you've come across some problems.

**Comment by LiHRaM** [comment]
@kubouch Yep, still working on it! I spend most of my time contributing to OSS in the weekends though. I've gotten it mostly working for the `path basename` command, working out some kinks for handling tables. It would be nice to have a chat about structuring some utility functions. Can I reach out on Discord?

**Comment by kubouch** [comment]
Sure, we can chat on Discord.

**Comment by fdncred** [comment]
@LiHRaM how's it going on this PR? We can land what we have and reassign the rest to someone else if you can't find the time.

**Comment by LiHRaM** [comment]
@fdncred We had some family over, which took up a lot of my spare time, but I would like to see how far I get this weekend before we reassign. I really want to tackle this, if that's okay with you. :)

**Comment by fdncred** [comment]
Ya,sure.

**Comment by LiHRaM** [comment]
@fdncred I feel pretty good about the progress I made today. I should be able to finish the rest after work tomorrow if I keep up this pace. 😄

**Comment by fdncred** [comment]
Looking good. We appreciate all your help. Keep up the good work!!!

**Comment by kubouch** [comment]
@LiHRaM Thanks for working on it! I think we don't need the Arc anymore in `operate()` etc. Engine-q simplified a few things so the Arc might not be required anymore.

**Comment by fdncred** [comment]
wow, you're cooking now. looks like we only have path join left. nice!.

**Comment by fdncred** [comment]
sorry to nag @LiHRaM, one more command left, so close. are you able to finish it?

**Comment by LiHRaM** [comment]
I'll have some time this weekend but if it's time critical I'm happy to hand this off to someone else.

**Comment by fdncred** [comment]
This weekend is fine. I'd like you to finish it since you've put so much effort into it. Thanks.

**Comment by fdncred** [comment]
ugh, I hate it when tests fail.

**Comment by LiHRaM** [comment]
It's officially waaaay past my bedtime. Tests should be passing now though, and I've checked that most of it works as intended, but I think an important part of review would probably just be comparing the output of engine-q and nushell for the examples included.

**Comment by jntrnr** [comment]
@LiHRaM - thanks for the work in porting these commands!

**Comment by fdncred** [comment]
@LiHRaM just wanted to say thanks for you staying up waaaaay past your bedtime :) and working so hard on completing these. we really appreciate all your hard work!

**Comment by kubouch** [comment]
@LiHRaM Woohoo, thanks a lot!

**Pull request merged**
