### PR TITLE
begin porting post

### PR DESCRIPTION
**Pull request by ghost**
I will get back this later next week when I am free.
Part of nushell/nushell#4356.

### CODE REVIEW

**Comment by efx** [comment]
## manual testing guide
You will need to start an HTTP server on localhost port 8080. I like miniserve. You can also use `nc`: `echo -ne "HTTP/1.0 200 OK\r\nConnection: close\r\n\r\nhello\n" | nc -l 8080`.

1. check out this branch
1. `cargo run -- -c 'post -k http://localhost:8080 (open README.md)'`

**Comment by jntrnr** [comment]
@efx - how's it going?

Just wanted to give a heads up that we'll be move this repo into the main nushell likely on Wednesday of next week. Don't mean to rush you, just didn't want to surprise you

**Comment by efx** [comment]
@jntrnr hey! Thank you for the heads up. I appreciate you being so considerate! 
I am slow going on this so may need to abandon.
I'll plan on giving it another try on Monday and then comment here with my progress.

**Comment by jntrnr** [comment]
Hi @efx - We're going to go ahead and close so we can prepare this repo to merge into Nushell main. Thanks for the work - after the merge with nushell, please feel free to reopen the PR there and continue the work.

Cheers

**Pull request closed without merging**
