### PR TITLE
allow fetch command to add custom headers

### PR DESCRIPTION
**Pull request by eggcaker**
allow to add more extra headers with two format ：
1. ``` fetch -H [k1 val1 k2 val2] url.com```
2. ``` fetch -H [[[k1 k2]; [val1 val2]] url.com```

### CODE REVIEW

**Comment by jntrnr** [comment]
@eggcaker - looks like you'll need to run one or more of these steps on your PR (if you haven't already):

* `cargo fmt` to give the code standard formatting
* `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
* `cargo build; cargo test --all --all-features` to check that all the tests pass

**Comment by eggcaker** [comment]
just tried run ```cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect``` 
got some errors from nu-json 
```
error: single-character string constant used as pattern
   --> crates/nu-system/src/linux.rs:206:54
    |
206 |                 cmd = cmd.replace("\n", " ").replace("\t", " ");
    |                                                      ^^^^ help: try using a `char` instead: `'\t'`
    |
    = note: `-D clippy::single-char-pattern` implied by `-D warnings`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#single_char_pattern

error: single-character string constant used as pattern
   --> crates/nu-system/src/linux.rs:206:35
    |
206 |                 cmd = cmd.replace("\n", " ").replace("\t", " ");
    |                                   ^^^^ help: try using a `char` instead: `'\n'`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#single_char_pattern

error: could not compile `nu-system` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: missing `#[must_use]` attribute on a method returning `Self`
  --> crates/nu-json/src/builder.rs:28:5
   |
28 | /     pub fn push<T: ser::Serialize>(mut self, v: T) -> ArrayBuilder {
29 | |         self.array
30 | |             .push(value::to_value(&v).expect("failed to serialize"));
31 | |         self
32 | |     }
   | |_____^
   |
   = note: `-D clippy::return-self-not-must-use` implied by `-D warnings`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#return_self_not_must_use

error: missing `#[must_use]` attribute on a method returning `Self`
  --> crates/nu-json/src/builder.rs:36:5
   |
36 | /     pub fn push_array<F>(mut self, f: F) -> ArrayBuilder
37 | |     where
38 | |         F: FnOnce(ArrayBuilder) -> ArrayBuilder,
39 | |     {
...  |
42 | |         self
43 | |     }
   | |_____^
```

**Comment by jntrnr** [comment]
@eggcaker - you may need to try it from the latest Rust stable. If you're on nightly, you may see additional warnings that aren't checked on the PR.

**Comment by jntrnr** [comment]
Looks like you got it fixed though

**Comment by jntrnr** [comment]
looks good!

**Pull request merged**
