### PR TITLE
Move fetch to extra and clean up some code

### PR DESCRIPTION
**Pull request by onthebridgetonowhere**
Moves fetch to extra (see #661) and cleans up some code.

### CODE REVIEW

**Comment by fdncred** [comment]
i'm conflicted about `fetch` being in extra. here's why.

reasons for moving it to extra
* we may want it in extra there because i think ssl is required and some platforms may have a problem with that.


reasons for not moving it to extra
* if we get to the place we want to be, which is recognizing when plugins are needed and automagically downloading them, we'll need `fetch` as a regular internal command.

**Comment by onthebridgetonowhere** [comment]
I definitely agree with the second part, when we need to download things automatically. So how about making it always available? Now we're not usyng `async` + `tokio` anymore, so the only crate needed is `reqwest`...

**Comment by jntrnr** [comment]
@fdncred are you thinking of making `fetch` part of the default features?

**Comment by jntrnr** [comment]
Ahh yeah, +1 on making it part of the default commands.

**Comment by fdncred** [comment]
ya, i think `default` is where we want to be with `fetch` to allow us to auto-download things in the future.

**Comment by onthebridgetonowhere** [comment]
I made it to be a default command :-)

**Comment by jntrnr** [comment]
thanks!

**Pull request merged**
