### PR TITLE
port over the append command from nushell

### PR DESCRIPTION
**Pull request by stormasm**
append a row or rows in a table...
append strings, ints, bools in a list...
reproduce functionality of the nushell append command...

### CODE REVIEW

**Comment by jntrnr** [comment]
This works a bit differently than the Nushell one. Not sure if we want to keep the Nushell approach or use this one. Here's the Nushell one:

```
> > [1, 2, 3] | append [4, 5, 6]
───┬────────────────
 0 │              1 
 1 │              2 
 2 │              3 
 3 │ [table 3 rows] 
───┴────────────────
```

**Comment by fdncred** [comment]
i personally like this better. in this statement, i read it like this; take the input list and append the items in the second list to it.
```
〉[1 2 3] | append [4 5 6]
╭───┬───╮
│ 0 │ 1 │
│ 1 │ 2 │
│ 2 │ 3 │
│ 3 │ 4 │
│ 4 │ 5 │
│ 5 │ 6 │
╰───┴───╯
```
if i wanted to do it the nushell way, i can still do this
```
〉[1 2 3] | append [[4 5 6]]
╭───┬───────────╮
│ 0 │ 1         │
│ 1 │ 2         │
│ 2 │ 3         │
│ 3 │ [4, 5, 6] │
╰───┴───────────╯
```

**Comment by stormasm** [comment]
[[name,age];[bill,20],[rick,21]] | append [[name,age]; [paul, 40], [hb,70], [sally, 333], [sam,46]]
╭───┬───────┬─────╮
│ # │ name  │ age │
├───┼───────┼─────┤
│ 0 │ bill  │ 20  │
│ 1 │ rick  │ 21  │
│ 2 │ paul  │ 40  │
│ 3 │ hb    │ 70  │
│ 4 │ sally │ 333 │
│ 5 │ sam   │ 46  │
╰───┴───────┴─────╯

**Comment by stormasm** [comment]
This was the one that took me the most time to seem correct, so I liked this one better....

**Comment by jntrnr** [comment]
Let's go for it

**Pull request merged**
