### PR TITLE
Fix error propagation across `hash` commands

### PR DESCRIPTION
**Pull request by CBenoit**
Example:

```
ls | get name | hash sha256
```

### CODE REVIEW

**Comment by fdncred** [comment]
I'm confused. What does this do exactly? This already works for me on Windows and Linux.
image

**Comment by CBenoit** [comment]
Oh. That's my bad, I originally tried the following and went wondering why it didn't work:

image

With this PR it's not getting any better as the output of cat is not getting piped as expected.

image

I guess all we need is to wait for `open` to be supported instead.

Let me repurpose this PR. I was originally just fixing the span / error when receiving an error value as input.

Before:
image

After:
image

**Comment by fdncred** [comment]
how about this `ls | where type == file | each {|r| (cat $r.name) | hash md5 }`

**Comment by CBenoit** [comment]
> how about this `ls | where type == file | each {|r| (cat $r.name) | hash md5 }`

Oh! Indeed, it works perfectly :ok_hand: 

And I push-forced to keep only the error propagation fix.

**Comment by fdncred** [comment]
oh, when the ci finishes we can land this.

**Comment by jntrnr** [comment]
looks good

**Pull request merged**
