### PR TITLE
Port `keep`, `keep while` and `keep until` commands

### PR DESCRIPTION
**Pull request by arthur-targaryen**
`keep n` was not listed in #242. I assume it's because `first(n)` would do the same, so I didn't implement it.

### CODE REVIEW

**Comment by jntrnr** [comment]
Can we also have a basic `keep` command so you can do `help keep` and see the subcommands?  We have that in a few places like `help str` and `help skip`.

**Comment by arthur-targaryen** [comment]
> Can we also have a basic `keep` command so you can do `help keep` and see the subcommands?

Yep, I'll add it ASAP 😄

**Comment by fdncred** [comment]
converted to draft until the requested changes are made. thanks for the work so far!

**Comment by fdncred** [comment]
@arthur-targaryen are you going to be able to finish this up or are you too bust at the moment?

**Comment by arthur-targaryen** [comment]
> @arthur-targaryen are you going to be able to finish this up or are you too busy at the moment?

Sorry I've been a bit busy. I'll find the time to finish this today!

**Comment by jntrnr** [comment]
Looks good!

**Pull request merged**
