### PR TITLE
Category option for signature

### PR DESCRIPTION
**Pull request by elferherrera**
Added a category method for signature to split commands by their type

### CODE REVIEW

**Comment by jntrnr** [comment]
nice

**Comment by fdncred** [comment]
this is great! if we're going for parity with nushell, we'll have to circle back at some point and add `is_custom` for the custom commands and the signature. i'm not exactly sure what `creates_scope` indicates for our users and i notice it's only true for the `for` command. I like having the extra detail.

one last thing i noticed, `help commands` doesn't highlight the word `commands` like a sub command.

**Comment by jntrnr** [comment]
We might also want to group all the flags together into their own record so we don't need quite so many columns

**Comment by fdncred** [comment]
ya, agreed. this pr exposed a problem in our new table functionality, which is, it doesn't have the `...` column when it's too wide, yet.

**Comment by jntrnr** [comment]
@fdncred hmm, it should have it. it's a port of `nu-table` from nushell. I wonder what's tripping it up

**Comment by fdncred** [comment]
It didn't work in windows. Did the ... work for you in Linux!

**Pull request merged**
